apiVersion: stackgres.io/v1
kind: SGConfig
metadata:
  name: test-cluster
spec:
  authentication:
    type: jwt
    user: admin
  cert:
    regenerateWebCert: false
  containerRegistry: quay.io
  developer:
    patches:
      clusterController:
        volumeMounts: []
  extensions:
    repositoryUrls:
    - https://extensions.stackgres.io/postgres/repository
  grafana:
    autoEmbed: false
    datasourceName: Prometheus
    password: prom-operator
    schema: http
    user: admin
  imagePullPolicy: IfNotPresent
  prometheus:
    allowAutobind: true
